<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 */
// The viewer should be loaded before the head to include the laminas header (css, js…).
$viewer = $this->universalViewer($resource);

$this->trigger('view.layout');

?>
<?= $this->doctype() ?>
<?= $this->htmlElement('html') ?>
    <head>
        <?= $this->headScript() ?>
    </head>
    <?= $this->htmlElement('body') ?>
        <?= $viewer ?>
    </body>
</html>
